### ISSUE TITLE
Router#match()がおかしい（インデントその他）

### ISSUE THREAD

**Issue by kwatch** [c-bata/webframework-in-python#8]
https://c-bata.link/webframework-in-python/routing.html#router のコードはインデントがおかしいです。おそらくタブを使ってしまったのだと思います。

```python
### before
    def match(self, method, path):
        for r in filter(lambda x: x['method'] == method.lower(), self.routes):
            matched = re.compile(r['path']).match(path)
         if matched:
             kwargs = matched.groupdict()
             return r, kwargs
     return http404, {}

### after
    def match(self, method, path):
        for r in filter(lambda x: x['method'] == method.lower(), self.routes):
            matched = re.compile(r['path']).match(path)
            if matched:
                kwargs = matched.groupdict()
                return r, kwargs
        return http404, {}
```

そのほか気づいた点です。

* `return r`は`return r['callback']`では？
* このコードだと、URLパスは合ってるけどリクエストメソッドが合わないときに、404が返されてしまいます。本来なら405を返すべきです。
* method.lower()を何回も呼び出す必要はないのでループの外に出しました。
* `re.compile().match()`は`re.match()`でいいです。
* できれば正規表現のコンパイルは`route()`の中で行い、`match()`の中ではしないほうがいいでしょう。

```python
### after
    def match(self, method, path):
        method = method.lower()
        http = http404
        for r in self.routes:
            matched = re.match(r['path'], path)
            if matched:
                http = http405
                if r['method'] == method:
                    kwargs = matched.groupdict()
                    return r['callback'], kwargs
        return http, {}
```

**Comment by c-bata** [comment]
お、確認しますね。

実はこの補足資料、途中で執筆に飽きてとりあえず雑にかきあげて放置していたものだったんですが、最近何故かはてぶが伸びたみたいなので雑な説明とか間違いがないか見直してちょうど修正しておこうかと思っていたところでした。なのでとてもありがたいです。

**Comment by c-bata** [comment]
ご指摘いただいた通りですね。ありがとうございました。

> できれば正規表現のコンパイルはroute()の中で行い、match()の中ではしないほうがいいでしょう。

おそらくお気づきだとは思うのですが、このあたりはあくまで解説目的のコードなのでシンプルさをとって対応しなかったという事情もあります。ここはおそらく今後も今のまま(Router#add()メソッドではcompileしない方針)にすると思います。

Method Not Allowedの対応とかは入れておこうと思います。

**Comment by c-bata** [comment]
https://github.com/c-bata/webframework-in-python/commit/28364d9e92fd16dbe1d7ab2d60ad6e7c6e400553 にてルーティングの説明を修正しました
